CREATE TABLE IF NOT EXISTS mitglieder (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  telefon VARCHAR(50),
  eintrittsdatum DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'aktiv',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
